package gui.控制台;

import static abc.Game.开服名字;
import static abc.Game.版本;
import static abc.sancu.FileDemo_05.删除文件;
import client.MapleCharacter;
import database.DatabaseConnection;
import database1.DatabaseConnection1;
import gui.Jieya.解压文件;
import static gui.Jieya.解压文件.解压文件;
import static gui.ZEVMS.下载文件;
import static a.本地数据库.数据库下载目录;
import static a.本地数据库.数据库导入目录;
import static a.本地数据库.数据库解压目录;
import static a.本地数据库.服务端数据库目录;
import static a.本地数据库.服务端目录;
import static gui.检测数据库表.检测数据库表;
import handling.channel.ChannelServer;
import handling.world.MapleParty;
import handling.world.World;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import provider.MapleData;
import provider.MapleDataProvider;
import provider.MapleDataProviderFactory;
import provider.MapleDataTool;
import org.jvnet.substance.skin.SubstanceBusinessBlackSteelLookAndFeel;
import scripting.NPCScriptManager;
import server.MapleInventoryManipulator;
import server.MapleItemInformationProvider;
import server.ServerProperties;
import server.events.MapleEvent;
import server.events.MapleEventType;
import tools.MaplePacketCreator;

/**
 *
 * @author Administrator
 */
public class 活动控制台 extends javax.swing.JFrame {

    /**
     * Creates new form 活动控制台
     */
    public 活动控制台() {
        ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource("gui/图片/pp/2.png"));
        setIconImage(icon.getImage());
        Properties 設定檔 = System.getProperties();

        setTitle("ZEVMS服务端后台 v" + 版本 + "<活动控制台> - < " + 开服名字 + " >");
        initComponents();
        MapleParty.出题间隔 = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        活动奖励 = new javax.swing.JPanel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        推雪球 = new javax.swing.JPanel();
        开启雪球赛 = new javax.swing.JButton();
        雪球赛频道 = new javax.swing.JTextField();
        jLabel328 = new javax.swing.JLabel();
        开始雪球赛 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel329 = new javax.swing.JLabel();
        jLabel342 = new javax.swing.JLabel();
        打椰子 = new javax.swing.JPanel();
        开启打椰子 = new javax.swing.JButton();
        打椰子频道 = new javax.swing.JTextField();
        开始打椰子 = new javax.swing.JButton();
        jLabel331 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel333 = new javax.swing.JLabel();
        打瓶盖 = new javax.swing.JPanel();
        开始打瓶盖 = new javax.swing.JButton();
        开启打瓶盖 = new javax.swing.JButton();
        打瓶盖频道 = new javax.swing.JTextField();
        jLabel337 = new javax.swing.JLabel();
        jLabel338 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        向高地 = new javax.swing.JPanel();
        开始向高地 = new javax.swing.JButton();
        开启向高地 = new javax.swing.JButton();
        向高地频道 = new javax.swing.JTextField();
        jLabel334 = new javax.swing.JLabel();
        jLabel335 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        OX答题 = new javax.swing.JPanel();
        开启OX答题 = new javax.swing.JButton();
        OX答题频道 = new javax.swing.JTextField();
        jLabel339 = new javax.swing.JLabel();
        jLabel343 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        OX答题平台 = new javax.swing.JPanel();
        OX问题 = new javax.swing.JTextField();
        发布问题 = new javax.swing.JButton();
        刷新题库 = new javax.swing.JButton();
        jLabel341 = new javax.swing.JLabel();
        运行状态 = new javax.swing.JLabel();
        倍率活动 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        开启双倍经验 = new javax.swing.JButton();
        双倍经验持续时间 = new javax.swing.JTextField();
        jLabel344 = new javax.swing.JLabel();
        开启双倍爆率 = new javax.swing.JButton();
        双倍爆率持续时间 = new javax.swing.JTextField();
        jLabel345 = new javax.swing.JLabel();
        开启双倍金币 = new javax.swing.JButton();
        双倍金币持续时间 = new javax.swing.JTextField();
        jLabel346 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        开启三倍经验 = new javax.swing.JButton();
        三倍经验持续时间 = new javax.swing.JTextField();
        jLabel347 = new javax.swing.JLabel();
        开启三倍爆率 = new javax.swing.JButton();
        三倍爆率持续时间 = new javax.swing.JTextField();
        jLabel348 = new javax.swing.JLabel();
        开启三倍金币 = new javax.swing.JButton();
        三倍金币持续时间 = new javax.swing.JTextField();
        jLabel349 = new javax.swing.JLabel();
        猜数字 = new javax.swing.JPanel();
        jScrollPane103 = new javax.swing.JScrollPane();
        猜数字答案 = new javax.swing.JTable();
        jScrollPane104 = new javax.swing.JScrollPane();
        消耗点券 = new javax.swing.JTable();
        jScrollPane105 = new javax.swing.JScrollPane();
        猜对次数 = new javax.swing.JTable();
        jScrollPane106 = new javax.swing.JScrollPane();
        猜错次数 = new javax.swing.JTable();
        jScrollPane107 = new javax.swing.JScrollPane();
        奖金池 = new javax.swing.JTable();
        jScrollPane108 = new javax.swing.JScrollPane();
        每次猜错增加消耗点券 = new javax.swing.JTable();
        刷新猜数字配置 = new javax.swing.JButton();
        奖金池增加 = new javax.swing.JTextField();
        奖金池增加1 = new javax.swing.JTextField();
        奖金池增加2 = new javax.swing.JTextField();
        奖金池增加3 = new javax.swing.JTextField();
        修改消耗点券 = new javax.swing.JButton();
        修改奖金池增加 = new javax.swing.JButton();
        修改奖金池 = new javax.swing.JButton();
        修改答案 = new javax.swing.JButton();

        setResizable(false);

        jTabbedPane5.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane5.setFont(new java.awt.Font("幼圆", 0, 15)); // NOI18N

        推雪球.setBackground(new java.awt.Color(255, 255, 255));
        推雪球.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "冒险岛活动：推雪球比赛", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("幼圆", 0, 24), new java.awt.Color(0, 0, 0))); // NOI18N
        推雪球.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        开启雪球赛.setFont(new java.awt.Font("幼圆", 0, 15)); // NOI18N
        开启雪球赛.setText("开启推雪球比赛");
        开启雪球赛.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                开启雪球赛ActionPerformed(evt);
            }
        });
        推雪球.add(开启雪球赛, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, -1, 30));
        推雪球.add(雪球赛频道, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 80, 30));

        jLabel328.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
        jLabel328.setText(" 一个频道只允许开启一个活动");
        推雪球.add(jLabel328, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, -1));

        开始雪球赛.setFont(new java.awt.Font("幼圆", 0, 15)); // NOI18N
        开始雪球赛.setText("开始推雪球比赛");
        开始雪球赛.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                开始雪球赛ActionPerformed(evt);
            }
        });
        推雪球.add(开始雪球赛, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 580, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/图片/活动图片/雪球赛.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        推雪球.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 590, -1));

        jLabel329.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
        jLabel329.setText("频道；");
        推雪球.add(jLabel329, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, -1, -1));

        jLabel342.setFont(new java.awt.Font("幼圆", 0, 15)); // NOI18N
        jLabel342.setText("待删除，整改");
        推雪球.add(jLabel342, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 20));

        jTabbedPane5.addTab("雪球赛", new javax.swing.ImageIcon(getClass().getResource("/gui/图片/pp/100.png")), 推雪球); // NOI18N

        打椰子.setBackground(new java.awt.Color(255, 255, 255));
        打椰子.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "冒险岛活动：打椰子比赛", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("幼圆", 0, 24), new java.awt.Color(0, 0, 0))); // NOI18N
        打椰子.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        开启打椰子.setFont(new java.awt.Font("幼圆", 0, 15)); // NOI18N
        开启打椰子.setText("开启打椰子比赛");
        开启打椰子.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                开启打椰子ActionPerformed(evt);
            }
        });
        打椰子.add(开启打椰子, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, -1, 30));
        打椰子.add(打椰子频道, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 80, 30));

        开始打椰子.setFont(new java.awt.Font("幼圆", 0, 15)); // NOI18N
        开始打椰子.setText("开始打椰子比赛");
        开始打椰子.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                开始打椰子ActionPerformed(evt);
            }
        });
        打椰子.add(开始打椰子, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 580, -1, 30));

        jLabel331.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
        jLabel331.setText("频道；");
        打椰子.add(jLabel331, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/图片/活动图片/椰子比赛.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        打椰子.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 590, -1));

        jLabel333.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
        jLabel333.setText(" 一个频道只允许开启一个活动");
        打椰子.add(jLabel333, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, -1));

        jTabbedPane5.addTab("打椰子", new javax.swing.ImageIcon(getClass().getResource("/gui/图片/pp/100.png")), 打椰子); // NOI18N

        打瓶盖.setBackground(new java.awt.Color(255, 255, 255));
        打瓶盖.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "冒险岛活动：打瓶盖比赛", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("幼圆", 0, 24), new java.awt.Color(0, 0, 0))); // NOI18N
        打瓶盖.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        开始打瓶盖.setFont(new java.awt.Font("幼圆", 0, 15)); // NOI18N
        开始打瓶盖.setText("开始打瓶盖比赛");
        开始打瓶盖.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                开始打瓶盖ActionPerformed(evt);
            }
        });
        打瓶盖.add(开始打瓶盖, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 580, -1, 30));

        开启打瓶盖.setFont(new java.awt.Font("幼圆", 0, 15)); // NOI18N
        开启打瓶盖.setText("开启打瓶盖比赛");
        开启打瓶盖.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                开启打瓶盖ActionPerformed(evt);
            }
        });
        打瓶盖.add(开启打瓶盖, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, -1, 30));
        打瓶盖.add(打瓶盖频道, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 80, 30));

        jLabel337.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
        jLabel337.setText("频道；");
        打瓶盖.add(jLabel337, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, -1, -1));

        jLabel338.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
        jLabel338.setText(" 一个频道只允许开启一个活动");
        打瓶盖.add(jLabel338, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/图片/活动图片/打瓶盖.png"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        打瓶盖.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 590, -1));

        jTabbedPane5.addTab("打瓶盖", new javax.swing.ImageIcon(getClass().getResource("/gui/图片/pp/100.png")), 打瓶盖); // NOI18N

        向高地.setBackground(new java.awt.Color(255, 255, 255));
        向高地.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "冒险岛活动：向高地比赛", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("幼圆", 0, 24), new java.awt.Color(0, 0, 0))); // NOI18N
        向高地.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        开始向高地.setFont(new java.awt.Font("幼圆", 0, 15)); // NOI18N
        开始向高地.setText("开始向高地比赛");
        开始向高地.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                开始向高地ActionPerformed(evt);
            }
        });
        向高地.add(开始向高地, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 580, -1, 30));

        开启向高地.setFont(new java.awt.Font("幼圆", 0, 15)); // NOI18N
        开启向高地.setText("开启向高地比赛");
        开启向高地.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                开启向高地ActionPerformed(evt);
            }
        });
        向高地.add(开启向高地, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, -1, 30));
        向高地.add(向高地频道, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 80, 30));

        jLabel334.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
        jLabel334.setText("频道；");
        向高地.add(jLabel334, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, -1, -1));

        jLabel335.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
        jLabel335.setText(" 一个频道只允许开启一个活动");
        向高地.add(jLabel335, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/图片/活动图片/向高地.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        向高地.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 590, -1));

        jTabbedPane5.addTab("向高地", new javax.swing.ImageIcon(getClass().getResource("/gui/图片/pp/100.png")), 向高地); // NOI18N

        OX答题.setBackground(new java.awt.Color(255, 255, 255));
        OX答题.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "冒险岛活动：OX答题比赛", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("幼圆", 0, 24), new java.awt.Color(0, 0, 0))); // NOI18N
        OX答题.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        开启OX答题.setFont(new java.awt.Font("幼圆", 0, 15)); // NOI18N
        开启OX答题.setText("开启OX答题比赛");
        开启OX答题.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                开启OX答题ActionPerformed(evt);
            }
        });
        OX答题.add(开启OX答题, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 580, -1, 30));
        OX答题.add(OX答题频道, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, 80, 30));

        jLabel339.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
        jLabel339.setText("频道；");
        OX答题.add(jLabel339, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, -1, -1));

        jLabel343.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
        jLabel343.setText(" 一个频道只允许开启一个活动");
        OX答题.add(jLabel343, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/图片/活动图片/OX答题.png"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        OX答题.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 590, -1));

        jTabbedPane5.addTab("OX答题", new javax.swing.ImageIcon(getClass().getResource("/gui/图片/pp/100.png")), OX答题); // NOI18N

        OX答题平台.setBackground(new java.awt.Color(255, 255, 255));
        OX答题平台.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "冒险岛活动：OX答题", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("幼圆", 0, 24), new java.awt.Color(0, 0, 0))); // NOI18N
        OX答题平台.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OX问题.setEditable(false);
        OX问题.setFont(new java.awt.Font("幼圆", 0, 18)); // NOI18N
        OX问题.setForeground(new java.awt.Color(204, 0, 51));
        OX问题.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OX问题ActionPerformed(evt);
            }
        });
        OX答题平台.add(OX问题, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 710, 40));

        发布问题.setFont(new java.awt.Font("幼圆", 0, 15)); // NOI18N
        发布问题.setText("发布问题");
        发布问题.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                发布问题ActionPerformed(evt);
            }
        });
        OX答题平台.add(发布问题, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 120, 40));

        刷新题库.setFont(new java.awt.Font("幼圆", 0, 15)); // NOI18N
        刷新题库.setText("刷新题库");
        刷新题库.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                刷新题库ActionPerformed(evt);
            }
        });
        OX答题平台.add(刷新题库, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 120, 40));

        jLabel341.setFont(new java.awt.Font("幼圆", 0, 15)); // NOI18N
        jLabel341.setText("出题区域；");
        OX答题平台.add(jLabel341, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 20));

        运行状态.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        运行状态.setForeground(new java.awt.Color(255, 0, 0));
        OX答题平台.add(运行状态, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 980, 30));

        jTabbedPane5.addTab("OX答题平台", new javax.swing.ImageIcon(getClass().getResource("/gui/图片/pp/100.png")), OX答题平台); // NOI18N

        倍率活动.setBackground(new java.awt.Color(255, 255, 255));
        倍率活动.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "倍率活动", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("幼圆", 0, 24), new java.awt.Color(0, 0, 0))); // NOI18N
        倍率活动.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "倍率活动", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("幼圆", 0, 24), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        开启双倍经验.setFont(new java.awt.Font("幼圆", 0, 15)); // NOI18N
        开启双倍经验.setText("开启双倍经验");
        开启双倍经验.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                开启双倍经验ActionPerformed(evt);
            }
        });
        jPanel1.add(开启双倍经验, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));
        jPanel1.add(双倍经验持续时间, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 120, -1));

        jLabel344.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
        jLabel344.setText("持续时间/h；");
        jPanel1.add(jLabel344, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 20));

        开启双倍爆率.setFont(new java.awt.Font("幼圆", 0, 15)); // NOI18N
        开启双倍爆率.setText("开启双倍爆率");
        开启双倍爆率.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                开启双倍爆率ActionPerformed(evt);
            }
        });
        jPanel1.add(开启双倍爆率, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));
        jPanel1.add(双倍爆率持续时间, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 120, -1));

        jLabel345.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
        jLabel345.setText("持续时间/h；");
        jPanel1.add(jLabel345, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 20));

        开启双倍金币.setFont(new java.awt.Font("幼圆", 0, 15)); // NOI18N
        开启双倍金币.setText("开启双倍金币");
        开启双倍金币.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                开启双倍金币ActionPerformed(evt);
            }
        });
        jPanel1.add(开启双倍金币, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));
        jPanel1.add(双倍金币持续时间, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 120, -1));

        jLabel346.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
        jLabel346.setText("持续时间/h；");
        jPanel1.add(jLabel346, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 20));

        倍率活动.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 330, 240));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "倍率活动", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("幼圆", 0, 24), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        开启三倍经验.setFont(new java.awt.Font("幼圆", 0, 15)); // NOI18N
        开启三倍经验.setText("开启三倍经验");
        开启三倍经验.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                开启三倍经验ActionPerformed(evt);
            }
        });
        jPanel2.add(开启三倍经验, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));
        jPanel2.add(三倍经验持续时间, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 120, -1));

        jLabel347.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
        jLabel347.setText("持续时间/h；");
        jPanel2.add(jLabel347, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 20));

        开启三倍爆率.setFont(new java.awt.Font("幼圆", 0, 15)); // NOI18N
        开启三倍爆率.setText("开启三倍爆率");
        开启三倍爆率.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                开启三倍爆率ActionPerformed(evt);
            }
        });
        jPanel2.add(开启三倍爆率, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));
        jPanel2.add(三倍爆率持续时间, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 120, -1));

        jLabel348.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
        jLabel348.setText("持续时间/h；");
        jPanel2.add(jLabel348, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 20));

        开启三倍金币.setFont(new java.awt.Font("幼圆", 0, 15)); // NOI18N
        开启三倍金币.setText("开启三倍金币");
        开启三倍金币.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                开启三倍金币ActionPerformed(evt);
            }
        });
        jPanel2.add(开启三倍金币, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));
        jPanel2.add(三倍金币持续时间, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 120, -1));

        jLabel349.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
        jLabel349.setText("持续时间/h；");
        jPanel2.add(jLabel349, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 20));

        倍率活动.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 330, 330));

        jTabbedPane5.addTab("倍率活动", new javax.swing.ImageIcon(getClass().getResource("/gui/图片/pp/100.png")), 倍率活动); // NOI18N

        猜数字.setBackground(new java.awt.Color(255, 255, 255));
        猜数字.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "猜数字", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("幼圆", 0, 24), new java.awt.Color(0, 0, 0))); // NOI18N
        猜数字.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        猜数字答案.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "答案"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        猜数字答案.setColumnSelectionAllowed(true);
        jScrollPane103.setViewportView(猜数字答案);
        猜数字答案.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (猜数字答案.getColumnModel().getColumnCount() > 0) {
            猜数字答案.getColumnModel().getColumn(0).setResizable(false);
        }

        猜数字.add(jScrollPane103, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 110, 60));

        消耗点券.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "消耗点券"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane104.setViewportView(消耗点券);
        消耗点券.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (消耗点券.getColumnModel().getColumnCount() > 0) {
            消耗点券.getColumnModel().getColumn(0).setResizable(false);
        }

        猜数字.add(jScrollPane104, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 110, 60));

        猜对次数.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "猜对次数"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane105.setViewportView(猜对次数);
        猜对次数.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (猜对次数.getColumnModel().getColumnCount() > 0) {
            猜对次数.getColumnModel().getColumn(0).setResizable(false);
        }

        猜数字.add(jScrollPane105, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 110, 60));

        猜错次数.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "猜错次数"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane106.setViewportView(猜错次数);
        猜错次数.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (猜错次数.getColumnModel().getColumnCount() > 0) {
            猜错次数.getColumnModel().getColumn(0).setResizable(false);
        }

        猜数字.add(jScrollPane106, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 110, 60));

        奖金池.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "奖金池"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane107.setViewportView(奖金池);
        奖金池.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (奖金池.getColumnModel().getColumnCount() > 0) {
            奖金池.getColumnModel().getColumn(0).setResizable(false);
        }

        猜数字.add(jScrollPane107, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 110, 60));

        每次猜错增加消耗点券.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "每次猜错增加消奖金"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane108.setViewportView(每次猜错增加消耗点券);
        每次猜错增加消耗点券.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (每次猜错增加消耗点券.getColumnModel().getColumnCount() > 0) {
            每次猜错增加消耗点券.getColumnModel().getColumn(0).setResizable(false);
        }

        猜数字.add(jScrollPane108, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 160, 60));

        刷新猜数字配置.setText("刷新");
        刷新猜数字配置.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                刷新猜数字配置ActionPerformed(evt);
            }
        });
        猜数字.add(刷新猜数字配置, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 110, 60));
        猜数字.add(奖金池增加, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 80, 30));
        猜数字.add(奖金池增加1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 80, 30));
        猜数字.add(奖金池增加2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 80, 30));
        猜数字.add(奖金池增加3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 80, 30));

        修改消耗点券.setText("修改");
        修改消耗点券.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                修改消耗点券ActionPerformed(evt);
            }
        });
        猜数字.add(修改消耗点券, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, 30));

        修改奖金池增加.setText("修改");
        修改奖金池增加.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                修改奖金池增加ActionPerformed(evt);
            }
        });
        猜数字.add(修改奖金池增加, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, 30));

        修改奖金池.setText("修改");
        修改奖金池.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                修改奖金池ActionPerformed(evt);
            }
        });
        猜数字.add(修改奖金池, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, -1, 30));

        修改答案.setText("修改");
        修改答案.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                修改答案ActionPerformed(evt);
            }
        });
        猜数字.add(修改答案, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, 30));

        jTabbedPane5.addTab("猜数字", new javax.swing.ImageIcon(getClass().getResource("/gui/图片/pp/100.png")), 猜数字); // NOI18N

        javax.swing.GroupLayout 活动奖励Layout = new javax.swing.GroupLayout(活动奖励);
        活动奖励.setLayout(活动奖励Layout);
        活动奖励Layout.setHorizontalGroup(
            活动奖励Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1260, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        活动奖励Layout.setVerticalGroup(
            活动奖励Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(活动奖励, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(活动奖励, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public int Getsaiji(String Name, int Channale) {
        int ret = -1;
        try {
            Connection con = DatabaseConnection.getConnection();
            PreparedStatement ps = con.prepareStatement("SELECT * FROM saiji WHERE channel = ? and Name = ?");
            ps.setInt(1, Channale);
            ps.setString(2, Name);
            ResultSet rs = ps.executeQuery();
            rs.next();
            ret = rs.getInt("Point");
            rs.close();
            ps.close();
        } catch (SQLException ex) {
        }
        return ret;
    }

    public void Gainsaiji(String Name, int Channale, int saiji) {
        try {
            int ret = Getsaiji(Name, Channale);
            if (ret == -1) {
                ret = 0;
                PreparedStatement ps = null;
                try {
                    ps = DatabaseConnection.getConnection().prepareStatement("INSERT INTO saiji (channel, Name,Point) VALUES (?, ?, ?)");
                    ps.setInt(1, Channale);
                    ps.setString(2, Name);
                    ps.setInt(3, ret);

                    ps.execute();
                } catch (SQLException e) {
                    System.out.println("xxxxxxxx:" + e);
                } finally {
                    try {
                        if (ps != null) {
                            ps.close();
                        }
                    } catch (SQLException e) {
                        System.out.println("xxxxxxxxzzzzzzz:" + e);
                    }
                }
            }
            ret += saiji;
            Connection con = DatabaseConnection.getConnection();
            PreparedStatement ps = con.prepareStatement("UPDATE saiji SET `Point` = ? WHERE Name = ? and channel = ?");
            ps.setInt(1, ret);
            ps.setString(2, Name);
            ps.setInt(3, Channale);
            ps.execute();
            ps.close();
        } catch (SQLException sql) {
            System.err.println("獲取錯誤!!55" + sql);
        }
    }

   

    private void 刷新猜数字配置ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_刷新猜数字配置ActionPerformed
        刷新猜数字配置();        // TODO add your handling code here:
    }//GEN-LAST:event_刷新猜数字配置ActionPerformed

    private void 修改奖金池增加ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_修改奖金池增加ActionPerformed
        boolean result1 = this.奖金池增加.getText().matches("[0-9]+");
        if (result1) {
            if (Integer.parseInt(this.奖金池增加.getText()) < 0) {
                JOptionPane.showMessageDialog(null, "请填写正确的值");
            }
            PreparedStatement ps1 = null;
            ResultSet rs = null;
            try {
                ps1 = DatabaseConnection.getConnection().prepareStatement("SELECT * FROM z猜数字 WHERE id = ?");
                ps1.setInt(1, 1);
                rs = ps1.executeQuery();
                if (rs.next()) {
                    String sqlstr = " delete from z猜数字 where id =1";
                    ps1.executeUpdate(sqlstr);

                }
            } catch (SQLException ex) {
                Logger.getLogger(活动控制台.class
                        .getName()).log(Level.SEVERE, null, ex);
            }

            try (Connection con = DatabaseConnection.getConnection(); PreparedStatement ps = con.prepareStatement("INSERT INTO z猜数字 (id, Name,Point,channel) VALUES (?, ?, ?, ?)")) {
                ps.setInt(1, 1);
                ps.setString(2, "每次猜错增加奖金");
                ps.setInt(3, Integer.parseInt(this.奖金池增加.getText()));
                ps.setInt(4, 1);
                ps.executeUpdate();
                刷新猜数字配置();

            } catch (SQLException ex) {
                Logger.getLogger(活动控制台.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_修改奖金池增加ActionPerformed

    private void 修改消耗点券ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_修改消耗点券ActionPerformed
        boolean result1 = this.奖金池增加2.getText().matches("[0-9]+");
        if (result1) {
            if (Integer.parseInt(this.奖金池增加2.getText()) < 0) {
                JOptionPane.showMessageDialog(null, "请填写正确的值");
            }
            PreparedStatement ps1 = null;
            ResultSet rs = null;
            try {
                ps1 = DatabaseConnection.getConnection().prepareStatement("SELECT * FROM z猜数字 WHERE id = ?");
                ps1.setInt(1, 2);
                rs = ps1.executeQuery();
                if (rs.next()) {
                    String sqlstr = " delete from z猜数字 where id =2";
                    ps1.executeUpdate(sqlstr);

                }
            } catch (SQLException ex) {
                Logger.getLogger(活动控制台.class
                        .getName()).log(Level.SEVERE, null, ex);
            }

            try (Connection con = DatabaseConnection.getConnection(); PreparedStatement ps = con.prepareStatement("INSERT INTO z猜数字 (id, Name,Point,channel) VALUES (?, ?, ?, ?)")) {
                ps.setInt(1, 2);
                ps.setString(2, "消耗点券");
                ps.setInt(3, Integer.parseInt(this.奖金池增加2.getText()));
                ps.setInt(4, 1);
                ps.executeUpdate();
                刷新猜数字配置();

            } catch (SQLException ex) {
                Logger.getLogger(活动控制台.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        }          // TODO add your handling code here:
    }//GEN-LAST:event_修改消耗点券ActionPerformed

    private void 修改答案ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_修改答案ActionPerformed
        boolean result1 = this.奖金池增加3.getText().matches("[0-9]+");
        if (result1) {
            if (Integer.parseInt(this.奖金池增加3.getText()) < 0) {
                JOptionPane.showMessageDialog(null, "请填写正确的值");
            }
            PreparedStatement ps1 = null;
            ResultSet rs = null;
            try {
                ps1 = DatabaseConnection.getConnection().prepareStatement("SELECT * FROM z猜数字 WHERE id = ?");
                ps1.setInt(1, 5);
                rs = ps1.executeQuery();
                if (rs.next()) {
                    String sqlstr = " delete from z猜数字 where id =5";
                    ps1.executeUpdate(sqlstr);

                }
            } catch (SQLException ex) {
                Logger.getLogger(活动控制台.class
                        .getName()).log(Level.SEVERE, null, ex);
            }

            try (Connection con = DatabaseConnection.getConnection(); PreparedStatement ps = con.prepareStatement("INSERT INTO z猜数字 (id, Name,Point,channel) VALUES (?, ?, ?, ?)")) {
                ps.setInt(1, 5);
                ps.setString(2, "猜数字答案");
                ps.setInt(3, Integer.parseInt(this.奖金池增加3.getText()));
                ps.setInt(4, 1);
                ps.executeUpdate();
                刷新猜数字配置();

            } catch (SQLException ex) {
                Logger.getLogger(活动控制台.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        }   // TODO add your handling code here:
    }//GEN-LAST:event_修改答案ActionPerformed

    private void 修改奖金池ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_修改奖金池ActionPerformed
        boolean result1 = this.奖金池增加1.getText().matches("[0-9]+");
        if (result1) {
            if (Integer.parseInt(this.奖金池增加1.getText()) < 0) {
                JOptionPane.showMessageDialog(null, "请填写正确的值");
            }
            PreparedStatement ps1 = null;
            ResultSet rs = null;
            try {
                ps1 = DatabaseConnection.getConnection().prepareStatement("SELECT * FROM z猜数字 WHERE id = ?");
                ps1.setInt(1, 6);
                rs = ps1.executeQuery();
                if (rs.next()) {
                    String sqlstr = " delete from z猜数字 where id =6";
                    ps1.executeUpdate(sqlstr);

                }
            } catch (SQLException ex) {
                Logger.getLogger(活动控制台.class
                        .getName()).log(Level.SEVERE, null, ex);
            }

            try (Connection con = DatabaseConnection.getConnection(); PreparedStatement ps = con.prepareStatement("INSERT INTO z猜数字 (id, Name,Point,channel) VALUES (?, ?, ?, ?)")) {
                ps.setInt(1, 6);
                ps.setString(2, "奖金池");
                ps.setInt(3, Integer.parseInt(this.奖金池增加1.getText()));
                ps.setInt(4, 1);
                ps.executeUpdate();
                刷新猜数字配置();

            } catch (SQLException ex) {
                Logger.getLogger(活动控制台.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        }         // TODO add your handling code here:
    }//GEN-LAST:event_修改奖金池ActionPerformed

    private void 开启雪球赛ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_开启雪球赛ActionPerformed
        boolean result1 = this.雪球赛频道.getText().matches("[0-9]+");
        if (result1) {
            if (Integer.parseInt(this.雪球赛频道.getText()) > Integer.parseInt(ServerProperties.getProperty("ZEV.Count"))) {
                JOptionPane.showMessageDialog(null, "输入的频道数量大于现有的频道数量");
                return;
            }
            final MapleEventType type = MapleEventType.getByString("雪球赛");
            if (type == null) {
                final StringBuilder sb = new StringBuilder("目前开放的活动有: ");
                for (MapleEventType t : MapleEventType.values()) {
                    sb.append(t.name()).append(",");
                }
                //dropMessage(5, sb.toString().substring(0, sb.toString().length() - 1));
            }
            final String msg = MapleEvent.scheduleEvent(type, ChannelServer.getInstance(Integer.parseInt(this.雪球赛频道.getText())));
            if (msg.length() > 0) {
                //c.getPlayer().dropMessage(5, msg);
            }
        } else {
            JOptionPane.showMessageDialog(null, "输入开始活动的频道");
        }
    }//GEN-LAST:event_开启雪球赛ActionPerformed

    private void 开始雪球赛ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_开始雪球赛ActionPerformed
        MapleEvent.setEvent(ChannelServer.getInstance(Integer.parseInt(this.雪球赛频道.getText())), true);
    }//GEN-LAST:event_开始雪球赛ActionPerformed

    private void 开启打椰子ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_开启打椰子ActionPerformed
        boolean result1 = this.打椰子频道.getText().matches("[0-9]+");
        if (result1) {
            if (Integer.parseInt(this.打椰子频道.getText()) > Integer.parseInt(ServerProperties.getProperty("ZEV.Count"))) {
                JOptionPane.showMessageDialog(null, "输入的频道数量大于现有的频道数量");
                return;
            }
            final MapleEventType type = MapleEventType.getByString("椰子比赛");
            final String msg = MapleEvent.scheduleEvent(type, ChannelServer.getInstance(Integer.parseInt(this.打椰子频道.getText())));
            if (msg.length() > 0) {
                //c.getPlayer().dropMessage(5, msg);
            }
        } else {
            JOptionPane.showMessageDialog(null, "输入开始活动的频道");
        }
    }//GEN-LAST:event_开启打椰子ActionPerformed

    private void 开始打椰子ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_开始打椰子ActionPerformed
        MapleEvent.setEvent(ChannelServer.getInstance(Integer.parseInt(this.打椰子频道.getText())), true);
    }//GEN-LAST:event_开始打椰子ActionPerformed

    private void 开始向高地ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_开始向高地ActionPerformed
        MapleEvent.setEvent(ChannelServer.getInstance(Integer.parseInt(this.向高地频道.getText())), true);
    }//GEN-LAST:event_开始向高地ActionPerformed

    private void 开启向高地ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_开启向高地ActionPerformed
        boolean result1 = this.向高地频道.getText().matches("[0-9]+");
        if (result1) {
            if (Integer.parseInt(this.向高地频道.getText()) > Integer.parseInt(ServerProperties.getProperty("ZEV.Count"))) {
                JOptionPane.showMessageDialog(null, "输入的频道数量大于现有的频道数量");
                return;
            }
            final MapleEventType type = MapleEventType.getByString("向高地");
            final String msg = MapleEvent.scheduleEvent(type, ChannelServer.getInstance(Integer.parseInt(this.向高地频道.getText())));
            if (msg.length() > 0) {
                //c.getPlayer().dropMessage(5, msg);
            }
        } else {
            JOptionPane.showMessageDialog(null, "输入开始活动的频道");
        }
    }//GEN-LAST:event_开启向高地ActionPerformed

    private void 开始打瓶盖ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_开始打瓶盖ActionPerformed
        MapleEvent.setEvent(ChannelServer.getInstance(Integer.parseInt(this.打瓶盖频道.getText())), true);
    }//GEN-LAST:event_开始打瓶盖ActionPerformed

    private void 开启打瓶盖ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_开启打瓶盖ActionPerformed
        boolean result1 = this.打瓶盖频道.getText().matches("[0-9]+");
        if (result1) {
            if (Integer.parseInt(this.打瓶盖频道.getText()) > Integer.parseInt(ServerProperties.getProperty("ZEV.Count"))) {
                JOptionPane.showMessageDialog(null, "输入的频道数量大于现有的频道数量");
                return;
            }
            final MapleEventType type = MapleEventType.getByString("打瓶盖");
            final String msg = MapleEvent.scheduleEvent(type, ChannelServer.getInstance(Integer.parseInt(this.打瓶盖频道.getText())));
            if (msg.length() > 0) {
                //c.getPlayer().dropMessage(5, msg);
            }
        } else {
            JOptionPane.showMessageDialog(null, "输入开始活动的频道");
        }
    }//GEN-LAST:event_开启打瓶盖ActionPerformed

    public void O() {
        for (ChannelServer cserv : ChannelServer.getAllInstances()) {
            for (MapleCharacter chr : cserv.getPlayerStorage().getAllCharacters()) {
                if (chr == null) {
                    continue;
                }
                if (chr.getMapId() == 109020001) {
                    double x = chr.getPosition().getX();
                    double y = chr.getPosition().getY();
                    if (x <= -307 && y > -200) {
                        NPCScriptManager.getInstance().dispose(chr.getClient());
                        NPCScriptManager.getInstance().start(chr.getClient(), 9000011, 4);
                        chr.dropMessage(1, "恭喜你选择了正确的答案");
                    } else {
                        chr.dropMessage(1, "很抱歉，你选择了不正确的答案");
                    }
                }
            }
        }
    }

    public void X() {
        for (ChannelServer cserv : ChannelServer.getAllInstances()) {
            for (MapleCharacter chr : cserv.getPlayerStorage().getAllCharacters()) {
                if (chr == null) {
                    continue;
                }
                if (chr.getMapId() == 109020001) {
                    double x = chr.getPosition().getX();
                    double y = chr.getPosition().getY();
                    if (x >= -146 && y > -200) {
                        NPCScriptManager.getInstance().dispose(chr.getClient());
                        NPCScriptManager.getInstance().start(chr.getClient(), 9000011, 4);
                        chr.dropMessage(1, "恭喜你选择了正确的答案");
                    } else {
                        chr.dropMessage(1, "很抱歉，你选择了不正确的答案");
                    }
                }
            }
        }
    }
    private void OX问题ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OX问题ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OX问题ActionPerformed

    private void 发布问题ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_发布问题ActionPerformed
//        String 输出 = "";
//
//        if (MapleParty.出题间隔 != 0) {
//            运行状态.setText("请等上一轮出题结束后再次出题。");
//            return;
//        }
//        if (OX问题.getText().equals("")) {
//            JOptionPane.showMessageDialog(null, "请从题库选择问题");
//            return;
//        }
//        try {
//            String str = OX问题.getText();
//            String 答案 = 录入答案.getText();
//            int 地图 = 109020001;
//            //int 时间 = Integer.parseInt(this.答题时间.getText());
//            for (ChannelServer cserv1 : ChannelServer.getAllInstances()) {
//                for (MapleCharacter mch : cserv1.getPlayerStorage().getAllCharacters()) {
//                    if (mch.getMapId() == 109020001) {
//                        mch.getMap().startMapEffect("OX答题:" + str, 5120027);
//                        mch.dropMessage(5, "[OX答题]: 30 秒后结算奖励，请各位玩家站在 “O” 区域或者“X”区域，其他区域没有结算奖励");
//                    }
//                }
//            }
//            MapleParty.出题间隔 = 1;
//            运行状态.setText("问题已经发布，30 秒后结算奖励，请耐心等候。");
//
//            MaplePacketCreator.getClock(10);
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "错误!\r\n" + e);
//        }
//        new Thread() {
//            @Override
//            public void run() {
//                //int 时间 = Integer.parseInt(this.答题时间.getText());
//                try {
//                    String 输出 = "";
//                    Thread.sleep(1000 * 30);
//                    if ("O".equals(录入答案.getText())) {
//                        O();
//                    }
//                    if ("X".equals(录入答案.getText())) {
//                        X();
//                    }
//                    MapleParty.出题间隔 = 0;
//                    运行状态.setText("结算完毕，可以开始下一轮。");
//                    /*输出 = "结算完毕，可以开始下一轮";
//                    运行状态("\r\n" + 输出);*/
//                } catch (InterruptedException e) {
//                }
//            }
//        }.start();
    }//GEN-LAST:event_发布问题ActionPerformed

    private void 刷新题库ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_刷新题库ActionPerformed
        //刷新题库();        // TODO add your handling code here:
    }//GEN-LAST:event_刷新题库ActionPerformed

    private void 开启OX答题ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_开启OX答题ActionPerformed
        boolean result1 = this.OX答题频道.getText().matches("[0-9]+");
        if (result1) {
            if (Integer.parseInt(this.OX答题频道.getText()) > Integer.parseInt(ServerProperties.getProperty("ZEV.Count"))) {
                JOptionPane.showMessageDialog(null, "输入的频道数量大于现有的频道数量");
                return;
            }
            final MapleEventType type = MapleEventType.getByString("答题");
            final String msg = MapleEvent.scheduleEvent(type, ChannelServer.getInstance(Integer.parseInt(this.OX答题频道.getText())));
            if (msg.length() > 0) {
                //c.getPlayer().dropMessage(5, msg);
            }
        } else {
            JOptionPane.showMessageDialog(null, "输入开始活动的频道");
        }

        /*boolean result1 = this.OX答题频道.getText().matches("[0-9]+");
        if (result1) {
            if (Integer.parseInt(this.OX答题频道.getText()) > Integer.parseInt(ServerProperties.getProperty("ZEV.Count"))) {
                JOptionPane.showMessageDialog(null, "输入的频道数量大于现有的频道数量");
                return;
            }
            World.Broadcast.broadcastSmega(MaplePacketCreator.serverNotice(9, Integer.parseInt(this.OX答题频道.getText()), "[活动] : " + Integer.parseInt(this.OX答题频道.getText()) + " 频道准备举行 [OX答题比赛] 活动,想要参加的玩家请进入等候室等待！"));

            final MapleEventType type = MapleEventType.getByString("答题");
        } else {
            JOptionPane.showMessageDialog(null, "输入开始活动的频道");
        }*/
    }//GEN-LAST:event_开启OX答题ActionPerformed

    private void 开启双倍经验ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_开启双倍经验ActionPerformed
        boolean result1 = this.双倍经验持续时间.getText().matches("[0-9]+");
        if (result1) {
            if (双倍经验持续时间.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "持续时间不能为空");
                return;
            }
            int 原始经验 = Integer.parseInt(ServerProperties.getProperty("ZEV.Exp"));
            int 双倍经验活动 = 原始经验 * 2;
            int seconds = 0;
            int mins = 0;
            int hours = Integer.parseInt(this.双倍经验持续时间.getText());
            int time = seconds + (mins * 60) + (hours * 60 * 60);
            final String rate = "经验";
            World.scheduleRateDelay(rate, time);
            for (ChannelServer cservs : ChannelServer.getAllInstances()) {
                cservs.setExpRate(双倍经验活动);
            }
            World.Broadcast.broadcastSmega(MaplePacketCreator.serverNotice(9, 20, "[倍率活动] : 游戏开始 2 倍打怪经验活动，将持续 " + hours + " 小时，请各位玩家狂欢吧！"));
            JOptionPane.showMessageDialog(null, "成功开启双倍经验活动，持续 " + hours + " 小时");
        } else {
            JOptionPane.showMessageDialog(null, "持续时间输入不正确");
        }
    }//GEN-LAST:event_开启双倍经验ActionPerformed

    private void 开启双倍爆率ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_开启双倍爆率ActionPerformed
        boolean result1 = this.双倍爆率持续时间.getText().matches("[0-9]+");
        if (result1) {
            if (双倍爆率持续时间.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "持续时间不能为空");
                return;
            }
            int 原始爆率 = Integer.parseInt(ServerProperties.getProperty("ZEV.Drop"));
            int 双倍爆率活动 = 原始爆率 * 2;
            int seconds = 0;
            int mins = 0;
            int hours = Integer.parseInt(this.双倍经验持续时间.getText());
            int time = seconds + (mins * 60) + (hours * 60 * 60);
            final String rate = "爆率";
            World.scheduleRateDelay(rate, time);
            for (ChannelServer cservs : ChannelServer.getAllInstances()) {
                cservs.setExpRate(双倍爆率活动);
            }
            World.Broadcast.broadcastSmega(MaplePacketCreator.serverNotice(9, 20, "[倍率活动] : 游戏开始 2 倍打怪爆率活动，将持续 " + hours + " 小时，请各位玩家狂欢吧！"));
            JOptionPane.showMessageDialog(null, "成功开启双倍爆率活动，持续 " + hours + " 小时");
        } else {
            JOptionPane.showMessageDialog(null, "持续时间输入不正确");
        }
    }//GEN-LAST:event_开启双倍爆率ActionPerformed

    private void 开启双倍金币ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_开启双倍金币ActionPerformed
        boolean result1 = this.双倍金币持续时间.getText().matches("[0-9]+");
        if (result1) {
            if (双倍金币持续时间.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "持续时间不能为空");
                return;
            }
            int 原始金币 = Integer.parseInt(ServerProperties.getProperty("ZEV.Meso"));
            int 双倍金币活动 = 原始金币 * 2;
            int seconds = 0;
            int mins = 0;
            int hours = Integer.parseInt(this.双倍金币持续时间.getText());
            int time = seconds + (mins * 60) + (hours * 60 * 60);
            final String rate = "金币";
            World.scheduleRateDelay(rate, time);
            for (ChannelServer cservs : ChannelServer.getAllInstances()) {
                cservs.setExpRate(双倍金币活动);
            }
            World.Broadcast.broadcastSmega(MaplePacketCreator.serverNotice(9, 20, "[倍率活动] : 游戏开始 2 倍打怪金币活动，将持续 " + hours + " 小时，请各位玩家狂欢吧！"));
            JOptionPane.showMessageDialog(null, "成功开启双倍金币活动，持续 " + hours + " 小时");
        } else {
            JOptionPane.showMessageDialog(null, "持续时间输入不正确");
        }
    }//GEN-LAST:event_开启双倍金币ActionPerformed

    private void 开启三倍经验ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_开启三倍经验ActionPerformed
        boolean result1 = this.三倍经验持续时间.getText().matches("[0-9]+");
        if (result1) {
            if (三倍经验持续时间.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "持续时间不能为空");
                return;
            }
            int 原始经验 = Integer.parseInt(ServerProperties.getProperty("ZEV.Exp"));
            int 三倍经验活动 = 原始经验 * 3;
            int seconds = 0;
            int mins = 0;
            int hours = Integer.parseInt(this.三倍经验持续时间.getText());
            int time = seconds + (mins * 60) + (hours * 60 * 60);
            final String rate = "经验";
            World.scheduleRateDelay(rate, time);
            for (ChannelServer cservs : ChannelServer.getAllInstances()) {
                cservs.setExpRate(三倍经验活动);
            }
            World.Broadcast.broadcastSmega(MaplePacketCreator.serverNotice(9, 20, "[倍率活动] : 游戏开始 3 倍打怪经验活动，将持续 " + hours + " 小时，请各位玩家狂欢吧！"));
            JOptionPane.showMessageDialog(null, "成功开启三倍经验活动，持续 " + hours + " 小时");
        } else {
            JOptionPane.showMessageDialog(null, "持续时间输入不正确");
        }
    }//GEN-LAST:event_开启三倍经验ActionPerformed

    private void 开启三倍爆率ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_开启三倍爆率ActionPerformed
        boolean result1 = this.三倍爆率持续时间.getText().matches("[0-9]+");
        if (result1) {
            if (三倍爆率持续时间.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "持续时间不能为空");
                return;
            }
            int 原始爆率 = Integer.parseInt(ServerProperties.getProperty("ZEV.Drop"));
            int 三倍爆率活动 = 原始爆率 * 3;
            int seconds = 0;
            int mins = 0;
            int hours = Integer.parseInt(this.三倍经验持续时间.getText());
            int time = seconds + (mins * 60) + (hours * 60 * 60);
            final String rate = "爆率";
            World.scheduleRateDelay(rate, time);
            for (ChannelServer cservs : ChannelServer.getAllInstances()) {
                cservs.setExpRate(三倍爆率活动);
            }
            World.Broadcast.broadcastSmega(MaplePacketCreator.serverNotice(9, 20, "[倍率活动] : 游戏开始 3 倍打怪爆率活动，将持续 " + hours + " 小时，请各位玩家狂欢吧！"));
            JOptionPane.showMessageDialog(null, "成功开启三倍爆率活动，持续 " + hours + " 小时");
        } else {
            JOptionPane.showMessageDialog(null, "持续时间输入不正确");
        }
    }//GEN-LAST:event_开启三倍爆率ActionPerformed

    private void 开启三倍金币ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_开启三倍金币ActionPerformed
        boolean result1 = this.三倍金币持续时间.getText().matches("[0-9]+");
        if (result1) {
            if (三倍金币持续时间.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "持续时间不能为空");
                return;
            }
            int 原始金币 = Integer.parseInt(ServerProperties.getProperty("ZEV.Meso"));
            int 三倍金币活动 = 原始金币 * 3;
            int seconds = 0;
            int mins = 0;
            int hours = Integer.parseInt(this.三倍金币持续时间.getText());
            int time = seconds + (mins * 60) + (hours * 60 * 60);
            final String rate = "金币";
            World.scheduleRateDelay(rate, time);
            for (ChannelServer cservs : ChannelServer.getAllInstances()) {
                cservs.setExpRate(三倍金币活动);
            }
            World.Broadcast.broadcastSmega(MaplePacketCreator.serverNotice(9, 20, "[倍率活动] : 游戏开始 3 倍打怪金币活动，将持续 " + hours + " 小时，请各位玩家狂欢吧！"));
            JOptionPane.showMessageDialog(null, "成功开启三倍金币活动，持续 " + hours + " 小时");
        } else {
            JOptionPane.showMessageDialog(null, "持续时间输入不正确");
        }
    }//GEN-LAST:event_开启三倍金币ActionPerformed

    public void 刷新猜数字配置() {

        for (int i = ((DefaultTableModel) (this.每次猜错增加消耗点券.getModel())).getRowCount() - 1; i >= 0; i--) {
            ((DefaultTableModel) (this.每次猜错增加消耗点券.getModel())).removeRow(i);
        }
        try {
            Connection con = DatabaseConnection.getConnection();
            PreparedStatement ps = null;

            ResultSet rs = null;
            ps = con.prepareStatement("SELECT * FROM z猜数字 WHERE id = 1");
            rs = ps.executeQuery();
            while (rs.next()) {
                ((DefaultTableModel) 每次猜错增加消耗点券.getModel()).insertRow(每次猜错增加消耗点券.getRowCount(), new Object[]{rs.getString("Point")});

            }
        } catch (SQLException ex) {
            Logger.getLogger(活动控制台.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        for (int i = ((DefaultTableModel) (this.消耗点券.getModel())).getRowCount() - 1; i >= 0; i--) {
            ((DefaultTableModel) (this.消耗点券.getModel())).removeRow(i);
        }
        try {
            Connection con = DatabaseConnection.getConnection();
            PreparedStatement ps = null;

            ResultSet rs = null;
            ps = con.prepareStatement("SELECT * FROM z猜数字 WHERE id = 2");
            rs = ps.executeQuery();
            while (rs.next()) {
                ((DefaultTableModel) 消耗点券.getModel()).insertRow(消耗点券.getRowCount(), new Object[]{rs.getString("Point")});

            }
        } catch (SQLException ex) {
            Logger.getLogger(活动控制台.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        for (int i = ((DefaultTableModel) (this.猜错次数.getModel())).getRowCount() - 1; i >= 0; i--) {
            ((DefaultTableModel) (this.猜错次数.getModel())).removeRow(i);
        }
        try {
            Connection con = DatabaseConnection.getConnection();
            PreparedStatement ps = null;

            ResultSet rs = null;
            ps = con.prepareStatement("SELECT * FROM z猜数字 WHERE id = 3");
            rs = ps.executeQuery();
            while (rs.next()) {
                ((DefaultTableModel) 猜错次数.getModel()).insertRow(猜错次数.getRowCount(), new Object[]{rs.getString("Point")});

            }
        } catch (SQLException ex) {
            Logger.getLogger(活动控制台.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        for (int i = ((DefaultTableModel) (this.猜对次数.getModel())).getRowCount() - 1; i >= 0; i--) {
            ((DefaultTableModel) (this.猜对次数.getModel())).removeRow(i);
        }
        try {
            Connection con = DatabaseConnection.getConnection();
            PreparedStatement ps = null;

            ResultSet rs = null;
            ps = con.prepareStatement("SELECT * FROM z猜数字 WHERE id = 4");
            rs = ps.executeQuery();
            while (rs.next()) {
                ((DefaultTableModel) 猜对次数.getModel()).insertRow(猜对次数.getRowCount(), new Object[]{rs.getString("Point")});

            }
        } catch (SQLException ex) {
            Logger.getLogger(活动控制台.class
                    .getName()).log(Level.SEVERE, null, ex);
        }

        for (int i = ((DefaultTableModel) (this.猜数字答案.getModel())).getRowCount() - 1; i >= 0; i--) {
            ((DefaultTableModel) (this.猜数字答案.getModel())).removeRow(i);
        }
        try {
            Connection con = DatabaseConnection.getConnection();
            PreparedStatement ps = null;

            ResultSet rs = null;
            ps = con.prepareStatement("SELECT * FROM z猜数字 WHERE id = 5");
            rs = ps.executeQuery();
            while (rs.next()) {
                ((DefaultTableModel) 猜数字答案.getModel()).insertRow(猜数字答案.getRowCount(), new Object[]{rs.getString("Point")});

            }
        } catch (SQLException ex) {
            Logger.getLogger(活动控制台.class
                    .getName()).log(Level.SEVERE, null, ex);
        }

        for (int i = ((DefaultTableModel) (this.奖金池.getModel())).getRowCount() - 1; i >= 0; i--) {
            ((DefaultTableModel) (this.奖金池.getModel())).removeRow(i);
        }
        try {
            Connection con = DatabaseConnection.getConnection();
            PreparedStatement ps = null;

            ResultSet rs = null;
            ps = con.prepareStatement("SELECT * FROM z猜数字 WHERE id = 6");
            rs = ps.executeQuery();
            while (rs.next()) {
                ((DefaultTableModel) 奖金池.getModel()).insertRow(奖金池.getRowCount(), new Object[]{rs.getString("Point")});

            }
        } catch (SQLException ex) {
            Logger.getLogger(活动控制台.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(活动控制台.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(活动控制台.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(活动控制台.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(活动控制台.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        活动控制台.setDefaultLookAndFeelDecorated(true);
        JDialog.setDefaultLookAndFeelDecorated(true);
        try {
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
            UIManager.setLookAndFeel(new SubstanceBusinessBlackSteelLookAndFeel());
            // UIManager.setLookAndFeel(new SubstanceBusinessLookAndFeel());
        } catch (Exception e) {
            e.printStackTrace();
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new 活动控制台().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel OX答题;
    private javax.swing.JPanel OX答题平台;
    private javax.swing.JTextField OX答题频道;
    private javax.swing.JTextField OX问题;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel328;
    private javax.swing.JLabel jLabel329;
    private javax.swing.JLabel jLabel331;
    private javax.swing.JLabel jLabel333;
    private javax.swing.JLabel jLabel334;
    private javax.swing.JLabel jLabel335;
    private javax.swing.JLabel jLabel337;
    private javax.swing.JLabel jLabel338;
    private javax.swing.JLabel jLabel339;
    private javax.swing.JLabel jLabel341;
    private javax.swing.JLabel jLabel342;
    private javax.swing.JLabel jLabel343;
    private javax.swing.JLabel jLabel344;
    private javax.swing.JLabel jLabel345;
    private javax.swing.JLabel jLabel346;
    private javax.swing.JLabel jLabel347;
    private javax.swing.JLabel jLabel348;
    private javax.swing.JLabel jLabel349;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane103;
    private javax.swing.JScrollPane jScrollPane104;
    private javax.swing.JScrollPane jScrollPane105;
    private javax.swing.JScrollPane jScrollPane106;
    private javax.swing.JScrollPane jScrollPane107;
    private javax.swing.JScrollPane jScrollPane108;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTextField 三倍爆率持续时间;
    private javax.swing.JTextField 三倍经验持续时间;
    private javax.swing.JTextField 三倍金币持续时间;
    private javax.swing.JButton 修改奖金池;
    private javax.swing.JButton 修改奖金池增加;
    private javax.swing.JButton 修改消耗点券;
    private javax.swing.JButton 修改答案;
    private javax.swing.JPanel 倍率活动;
    private javax.swing.JButton 刷新猜数字配置;
    private javax.swing.JButton 刷新题库;
    private javax.swing.JTextField 双倍爆率持续时间;
    private javax.swing.JTextField 双倍经验持续时间;
    private javax.swing.JTextField 双倍金币持续时间;
    private javax.swing.JButton 发布问题;
    private javax.swing.JPanel 向高地;
    private javax.swing.JTextField 向高地频道;
    private javax.swing.JTable 奖金池;
    private javax.swing.JTextField 奖金池增加;
    private javax.swing.JTextField 奖金池增加1;
    private javax.swing.JTextField 奖金池增加2;
    private javax.swing.JTextField 奖金池增加3;
    private javax.swing.JButton 开启OX答题;
    private javax.swing.JButton 开启三倍爆率;
    private javax.swing.JButton 开启三倍经验;
    private javax.swing.JButton 开启三倍金币;
    private javax.swing.JButton 开启双倍爆率;
    private javax.swing.JButton 开启双倍经验;
    private javax.swing.JButton 开启双倍金币;
    private javax.swing.JButton 开启向高地;
    private javax.swing.JButton 开启打椰子;
    private javax.swing.JButton 开启打瓶盖;
    private javax.swing.JButton 开启雪球赛;
    private javax.swing.JButton 开始向高地;
    private javax.swing.JButton 开始打椰子;
    private javax.swing.JButton 开始打瓶盖;
    private javax.swing.JButton 开始雪球赛;
    private javax.swing.JPanel 打椰子;
    private javax.swing.JTextField 打椰子频道;
    private javax.swing.JPanel 打瓶盖;
    private javax.swing.JTextField 打瓶盖频道;
    private javax.swing.JPanel 推雪球;
    private javax.swing.JTable 每次猜错增加消耗点券;
    private javax.swing.JPanel 活动奖励;
    private javax.swing.JTable 消耗点券;
    private javax.swing.JTable 猜对次数;
    private javax.swing.JPanel 猜数字;
    private javax.swing.JTable 猜数字答案;
    private javax.swing.JTable 猜错次数;
    private javax.swing.JLabel 运行状态;
    private javax.swing.JTextField 雪球赛频道;
    // End of variables declaration//GEN-END:variables

    void setText(String 活动控制台) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    void addActionListener(ActionListener actionListener) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
