/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.控制台.活动;

import gui.控制台.控制台2号;
import static abc.Game.窗口标题;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.UIManager;
import org.jvnet.substance.skin.SubstanceBusinessBlackSteelLookAndFeel;

/**
 *
 * @author Administrator
 */
public class 夺旗对抗赛 extends javax.swing.JFrame {

    /**
     * Creates new form 锻造控制台
     */
    public 夺旗对抗赛() {
        ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource("gui/图片/pp/2.png"));
        setIconImage(icon.getImage());
        setTitle("" + 窗口标题 + "【夺旗对抗赛】");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        蓝方旗帜地图y = new javax.swing.JTextField();
        蓝方旗帜地图 = new javax.swing.JTextField();
        蓝方旗帜地图2 = new javax.swing.JTextField();
        蓝方旗帜地图x = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        红方旗帜地图y = new javax.swing.JTextField();
        红方旗帜地图 = new javax.swing.JTextField();
        蓝方旗帜地图6 = new javax.swing.JTextField();
        红方旗帜地图x = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("幼圆", 0, 18)); // NOI18N
        jLabel1.setText("y；");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 50, -1));

        蓝方旗帜地图y.setText("20");
        jPanel1.add(蓝方旗帜地图y, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 70, -1));

        蓝方旗帜地图.setText("100000000");
        jPanel1.add(蓝方旗帜地图, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 110, -1));

        蓝方旗帜地图2.setText("100000000");
        jPanel1.add(蓝方旗帜地图2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 110, -1));

        蓝方旗帜地图x.setText("10");
        jPanel1.add(蓝方旗帜地图x, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 70, -1));

        jLabel2.setFont(new java.awt.Font("幼圆", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setText("蓝色方旗帜：");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 150, 40));

        jLabel3.setFont(new java.awt.Font("幼圆", 0, 18)); // NOI18N
        jLabel3.setText("地图；");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 80, -1));

        jLabel4.setFont(new java.awt.Font("幼圆", 0, 18)); // NOI18N
        jLabel4.setText("x；");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 50, -1));

        jLabel5.setFont(new java.awt.Font("幼圆", 0, 18)); // NOI18N
        jLabel5.setText("y；");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 50, -1));

        红方旗帜地图y.setText("20");
        jPanel1.add(红方旗帜地图y, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 70, -1));

        红方旗帜地图.setText("100000000");
        jPanel1.add(红方旗帜地图, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 110, -1));

        蓝方旗帜地图6.setText("100000000");
        jPanel1.add(蓝方旗帜地图6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 110, -1));

        红方旗帜地图x.setText("10");
        jPanel1.add(红方旗帜地图x, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 70, -1));

        jLabel6.setFont(new java.awt.Font("幼圆", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 51));
        jLabel6.setText("红色方旗帜：");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 150, 40));

        jLabel7.setFont(new java.awt.Font("幼圆", 0, 18)); // NOI18N
        jLabel7.setText("地图；");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 80, -1));

        jLabel8.setFont(new java.awt.Font("幼圆", 0, 18)); // NOI18N
        jLabel8.setText("x；");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 50, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

 
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(控制台2号.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        夺旗对抗赛.setDefaultLookAndFeelDecorated(true);
        JDialog.setDefaultLookAndFeelDecorated(true);
        try {
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
            UIManager.setLookAndFeel(new SubstanceBusinessBlackSteelLookAndFeel());
            // UIManager.setLookAndFeel(new SubstanceBusinessLookAndFeel());
        } catch (Exception e) {
            e.printStackTrace();
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new 夺旗对抗赛().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField 红方旗帜地图;
    private javax.swing.JTextField 红方旗帜地图x;
    private javax.swing.JTextField 红方旗帜地图y;
    private javax.swing.JTextField 蓝方旗帜地图;
    private javax.swing.JTextField 蓝方旗帜地图2;
    private javax.swing.JTextField 蓝方旗帜地图6;
    private javax.swing.JTextField 蓝方旗帜地图x;
    private javax.swing.JTextField 蓝方旗帜地图y;
    // End of variables declaration//GEN-END:variables
}
