package handling;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Properties;

public enum SendPacketOpcode implements WritableIntValueHolder {
//GENERAL//0x14)
    PING,
    //LOGIN-79//0x00)
    LOGIN_STATUS,
    PIN_OPERATION,
    SECONDPW_ERROR,
    //服务器列表//0x09),
    SERVERLIST,
    //服务器状态//0x06),
    SERVERSTATUS,
    //服务器IP//0x0B),
    SERVER_IP,
    //人物列表//0x0A),
    CHARLIST,
    //检查人物名反馈//0x0C),
    CHAR_NAME_RESPONSE,
    //0x16),
    RELOG_RESPONSE,
    //增加新人物//0x11),
    ADD_NEW_CHAR_ENTRY,
    //删除角色//0xFF),
    DELETE_CHAR_RESPONSE,
    //0x18),
    CHANNEL_SELECTED,
    ALL_CHARLIST,
    //选择性别//0x04),
    CHOOSE_GENDER,
    //性别选择返回
    GENDER_SET,//0x05),
    //抵用卷//0x7D),
    CHAR_CASH,
    //频道更换
    CHANGE_CHANNEL,
    //更新能力值//0x22),
    UPDATE_STATS,
    //人气反馈//0x29),
    FAME_RESPONSE,
    //更新技能//0x27),
    UPDATE_SKILLS,
    //更新技能//0x28),
    SKILL_USE_RESULT,
    //传送到地图//0x81),
    WARP_TO_MAP,
    //服务器公告//0x41),
    SERVERMESSAGE,
    //情景喇叭//0x56),
    AVATAR_MEGA,
    SPAWN_NPC,
    REMOVE_NPC,
    SPAWN_NPC_REQUEST_CONTROLLER,
    SPAWN_MONSTER,
    SPAWN_MONSTER_CONTROL,
    MOVE_MONSTER_RESPONSE,
    //聊天信息//0xA4),
    CHATTEXT,
    //人物具体信息//0x2A),
    SHOW_STATUS_INFO,
    SHOW_MESO_GAIN,
    //任务完成效果//0x33),
    SHOW_QUEST_COMPLETION,
    //悄悄话//0x8B),
    WHISPER,
    //配偶聊天//0x8C),
    SPOUSE_CHAT,
    //0xA2),
    SPAWN_PLAYER,
    ANNOUNCE_PLAYER_SHOP,
    SHOW_SCROLL_EFFECT,
    SHOW_ITEM_GAIN_INCHAT,
    DOJO_WARP_UP,
    CURRENT_MAP_WARP,
    KILL_MONSTER,
    DROP_ITEM_FROM_MAPOBJECT,
    FACIAL_EXPRESSION,
    MOVE_PLAYER,
    MOVE_MONSTER,
    CLOSE_RANGE_ATTACK,
    RANGED_ATTACK,
    MAGIC_ATTACK,
    ENERGY_ATTACK,
    OPEN_NPC_SHOP,
    CONFIRM_SHOP_TRANSACTION,
    OPEN_STORAGE,
    //道具栏信息//0x20),
    MODIFY_INVENTORY_ITEM,
    //移除玩家//0xA3),
    REMOVE_PLAYER_FROM_MAP,
    REMOVE_ITEM_FROM_MAP,
    UPDATE_CHAR_LOOK,
    SHOW_FOREIGN_EFFECT,
    GIVE_FOREIGN_BUFF,
    CANCEL_FOREIGN_BUFF,
    DAMAGE_PLAYER,
    //角色信息//0x3A),
    CHAR_INFO,
    UPDATE_QUEST_INFO,
    //获得增益效果状态//0x23),
    GIVE_BUFF,
    //取消增益效果状态//0x24),
    CANCEL_BUFF,
    PLAYER_INTERACTION,
    UPDATE_CHAR_BOX,
    NPC_TALK,
    KEYMAP,
    SHOW_MONSTER_HP,
    //开启组队//0x3B),
    PARTY_OPERATION,
    UPDATE_PARTYMEMBER_HP,
    //组队家族聊天//0x8A),
    MULTICHAT,
    APPLY_MONSTER_STATUS,
    CANCEL_MONSTER_STATUS,
    //时钟//0x96),
    CLOCK,
    //召唤门//0x40),
    SPAWN_PORTAL,
    SPAWN_DOOR,
    REMOVE_DOOR,
    SPAWN_SUMMON,
    REMOVE_SUMMON,
    SUMMON_ATTACK,
    MOVE_SUMMON,
    SPAWN_MIST,
    REMOVE_MIST,
    DAMAGE_SUMMON,
    DAMAGE_MONSTER,
    //好友列表
    BUDDYLIST,//0x3C),
    SHOW_ITEM_EFFECT,
    SHOW_CHAIR,
    CANCEL_CHAIR,
    SKILL_EFFECT,
    CANCEL_SKILL_EFFECT,
    //BOSS血条//0x8D),
    BOSS_ENV,
    REACTOR_SPAWN,
    REACTOR_HIT,
    REACTOR_DESTROY,
    //地图效果//0x91),
    MAP_EFFECT,
    //家族操作//0x3E),
    GUILD_OPERATION,
    //家族联盟//0x3F),
    ALLIANCE_OPERATION,
    //弹出管理员窗口7400010001
    //0x77),
    BBS_OPERATION,
    //拒绝登陆为同学。//0x6A),
    FAMILY,
    EARN_TITLE_MSG,
    SHOW_MAGNET,
    MERCH_ITEM_MSG,
    MERCH_ITEM_STORE,
    MESSENGER,
    NPC_ACTION,
    SPAWN_PET,
    MOVE_PET,
    PET_CHAT,
    PET_COMMAND,
    PET_NAMECHANGE,
    PET_FLAG_CHANGE,
    QUEST_ITEM_INFO,
    COOLDOWN,
    PLAYER_HINT,
    SUMMON_HINT,
    SUMMON_HINT_MSG,
    CYGNUS_INTRO_DISABLE_UI,
    CYGNUS_INTRO_LOCK,
    //使用技能书//0x35),
    USE_SKILL_BOOK,
    //0x89),
    SHOW_EQUIP_EFFECT,
    //技能宏//0x80),
    SKILL_MACRO,
    //进入商城//0x83),
    CS_OPEN,
    CS_UPDATE,
    CS_OPERATION,
    //进入拍卖//0x82),
    MTS_OPEN,
    //玩家NPC//0x5A),
    PLAYER_NPC,
    //小纸条//0x2B),
    SHOW_NOTES,
    SUMMON_SKILL,
    ARIANT_PQ_START,
    CATCH_MONSTER,
    CATCH_ARIANT,
    //阿里安特系列//0x9D),
    ARIANT_SCOREBOARD,
    ZAKUM_SHRINE,
    //船效果//,//short) 0x97),
    BOAT_EFFECT,
    //,//short) 0x98),
    BOAT_PACKET,
    CHALKBOARD,
    DUEY,
    //缩地石//0x2C),
    TROCK_LOCATIONS,
    //0x2D),
    LIE_DETECTOR,
    // LIE_DETECTOR_SKILL,//0x65),
    //确认测谎验证码
    LIE_DETECTOR_RESPONSE,//0x65),
    //刷新测谎验证码
    LIE_DETECTOR_REFRESH,//0x66),
    //0x2F),
    CLAIM_RESULT,
    //0x30),
    CLAIM_STATUS_CHANGED,
    //0x31),
    SET_TAMING_MOB_INFO,
    MONSTER_CARNIVAL_START,
    MONSTER_CARNIVAL_OBTAINED_CP,
    MONSTER_CARNIVAL_PARTY_CP,
    MONSTER_CARNIVAL_SUMMON,
    MONSTER_CARNIVAL_SUMMON1,
    MONSTER_CARNIVAL_DIED,
    SPAWN_HIRED_MERCHANT,
    UPDATE_HIRED_MERCHANT,
    //箱子？//0x34),
    SEND_TITLE_BOX,
    DESTROY_HIRED_MERCHANT,
    //更新骑宠//0x32),
    UPDATE_MOUNT,
    //怪物卡//0x5B),
    MONSTERBOOK_ADD,
    //0x5C),
    MONSTERBOOK_CHANGE_COVER,
    //装备道具获得经验提示//0x63),
    FAIRY_PEND_MSG,
    VICIOUS_HAMMER,
    //0x75),
    FISHING_BOARD_UPDATE,
    //0x74),
    DATA_CRC_CHECK_FAILED,
    FISHING_CAUGHT,
    //OX答题//0x94),
    OX_QUIZ,
    ROLL_SNOWBALL,
    HIT_SNOWBALL,
    SNOWBALL_MESSAGE,
    LEFT_KNOCK_BACK,
    //0x36),
    FINISH_SORT,
    //0x37),
    FINISH_GATHER,
    //打开学院-79//0x64),
    SEND_PEDIGREE,
    //0x65),
    OPEN_FAMILY,
    //0x66),
    FAMILY_MESSAGE,
    //0x67),
    FAMILY_INVITE,
    //0x68),
    FAMILY_JUNIOR,
    //0x69),
    SENIOR_MESSAGE,
    //成为了你的老师。在游戏过程中你可以获得各种的帮助。
    //0x6B),
    REP_INCREASE,
    //0x6C),
    FAMILY_LOGGEDIN,
    //0x6D),
    FAMILY_BUFF,
    //0x6E),
    FAMILY_USE_REQUEST,
    //聊天窗显示黄色字体//0x4E),
    YELLOW_CHAT,
    PIGMI_REWARD,
    //GM效果//0x93),
    GM_EFFECT,
    HIT_COCONUT,
    COCONUT_SCORE,
    //0x6F),
    LEVEL_UPDATE,
    //<家族>结婚了。大家祝福下他（她）吧！结婚提示//0x70
    MARRIAGE_UPDATE,
    //<家族>专职为新手？？转职提示 //0x71
    JOB_UPDATE,
    //项链扩充?//0x71),
    SET_BUY_EQUIP_EXT,
    HORNTAIL_SHRINE,
    //停止时钟//0x9C),
    STOP_CLOCK,
    MESOBAG_SUCCESS,
    MESOBAG_FAILURE,
    SERVER_BLOCKED,
    DRAGON_MOVE,
    DRAGON_REMOVE,
    DRAGON_SPAWN,
    ARAN_COMBO,
    矛连击强化,
    //顶部的公告//0x73),
    TOP_MSG,
    //临时能力值开始//0x25),
    TEMP_STATS,
    //临时能力值结束//0x26),
    TEMP_STATS_RESET,
    TUTORIAL_SUMMON,
    REPAIR_WINDOW,
    //0x9F),
    PYRAMID_UPDATE,
    //0xA0),
    PYRAMID_RESULT,
    //武林道场能量//0x62),
    ENERGY,
    GET_MTS_TOKENS,
    MTS_OPERATION,
    SHOW_POTENTIAL_EFFECT,
    SHOW_POTENTIAL_RESET,
    CHAOS_ZAKUM_SHRINE,
    CHAOS_HORNTAIL_SHRINE,
    GAME_POLL_QUESTION,
    GAME_POLL_REPLY,
    //GM活动命令-790X问答提示//0x95),
    GMEVENT_INSTRUCTIONS,
    BOAT_EFF,
    //搜索器//0x45),
    OWL_OF_MINERVA,
    XMAS_SURPRISE,
    //音乐盒//0x92),
    CASH_SONG,
    //道具栏信息//0x21),
    UPDATE_INVENTORY_SLOT,
    FOLLOW_REQUEST,
    FOLLOW_EFFECT,
    FOLLOW_MOVE,
    FOLLOW_MSG,
    FOLLOW_MESSAGE,
    TALK_MONSTER,
    REMOVE_TALK_MONSTER,
    MONSTER_PROPERTIES,
    //0xFF),
    MOVE_PLATFORM,
    MOVE_ENV,
    UPDATE_ENV,
    //离婚包//0x49),
    ENGAGE_REQUEST,
    //0x62),
    GHOST_POINT,
    GHOST_STATUS,
    //离婚包消息//0x4A),
    ENGAGE_RESULT,
    ENGLISH_QUIZ,
    ARIANT_SCORE_UPDATE,
    RPS_GAME,
    UPDATE_BEANS,
    BEANS_GAME_MESSAGE,
    //返回错误信息//0x87),
    BLOCK_MSG,
    AUTO_HP_POT,
    AUTO_MP_POT,
    //许可协议//0x02),
    LICENSE_RESULT,
    SPAWN_LOVE,
    REMOVE_LOVE,
    //地图装备效果//0x8F),
    FORCED_MAP_EQUIP,
    //塔罗牌//0x46),
    SHOW_PREDICT_CARD,
    BEANS_TIPS,
    BEANS_GAME1,
    BEANS_GAME2,
    //打开网站链接//0x76),
    OPEN_WEB;
    private short code = -2;

    @Override
    public void setValue(short code) {
        this.code = code;
    }

    @Override
    public short getValue() {
        return code;
    }

    public static Properties getDefaultProperties() throws FileNotFoundException, IOException {
        Properties props = new Properties();
        try (FileInputStream fileInputStream = new FileInputStream("Load\\send.ini")) {
            props.load(fileInputStream);
        }
        return props;
    }

    public static boolean isSpamHeader(SendPacketOpcode opcode) {
        switch (opcode.name()) {
            case "WARP_TO_MAP":
            case "PING":
            case "NPC_ACTION":
            case "UPDATE_STATS":
            case "MOVE_PLAYER":
            case "SPAWN_NPC":
            case "SPAWN_NPC_REQUEST_CONTROLLER":
            case "REMOVE_NPC":
            case "MOVE_MONSTER":
            case "MOVE_MONSTER_RESPONSE":
            case "SPAWN_MONSTER":
            case "SPAWN_MONSTER_CONTROL":
            case "ANDROID_MOVE":
                return true;
            default:
                return false;
        }
    }

    static {
        reloadValues();
    }

    public static final void reloadValues() {
        try {
            ExternalCodeTableGetter.populateValues(getDefaultProperties(), values());
        } catch (IOException e) {
            throw new RuntimeException("Failed to load sendops", e);
        }
    }
}
